services:
  server:
    container_name: server
    build:
      context: .
    expose:
      - 8000
    networks:
      - app_network

  nginx:
    container_name: nginx
    restart: always
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
