services:
  server:
    build:
      context: .
    expose:
      - 8000

  nginx:
    container_name: nginx
    restart: always
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app_network
